

target 'BerryPlant_Example' do
  pod 'BerryPlant', :path => '../'

  target 'BerryPlant_Tests' do
    inherit! :search_paths

    
  end
end


post_install do |installer|
    FixBerryUmbrella()
end


def FixBerryUmbrella
    berry_unbrella_file_path = (Dir::pwd + '/Pods/Headers/Public/BerryPlant/BerryPlant-umbrella.h')
    File.open(berry_unbrella_file_path,"r:utf-8") do |lines|
        buffer = lines.read
        buffer = buffer.gsub("decode.h","WebP/decode.h")
        buffer = buffer.gsub("encode.h","WebP/encode.h")
        buffer = buffer.gsub("types.h","WebP/types.h")
        File.open(berry_unbrella_file_path,"w"){|l|
            l.write(buffer)
        }
    end
end

