

platform :ios, '9.0'
target 'BerryPlant_Example' do
    pod 'BerryPlant', :path => '../'
  
end
target 'BerryPlant_Tests' do
    pod 'BerryPlant', :path => '../'
end

post_install do |installer|
#    FixBerryUmbrella()
end


def FixBerryUmbrella
    berry_unbrella_file_path = (Dir::pwd + '/Pods/Headers/Public/BerryPlant/BerryPlant-umbrella.h')
    File.open(berry_unbrella_file_path,"r:utf-8") do |lines|
        buffer = lines.read
        buffer = buffer.gsub('FOUNDATION_EXPORT double BerryPlantVersionNumber;','#import "WebP/decode.h"
                             #import "WebP/encode.h"
                             #import "WebP/types.h"
                             FOUNDATION_EXPORT double BerryPlantVersionNumber;')
        File.open(berry_unbrella_file_path,"w"){|l|
            l.write(buffer)
        }
    end
end

